# fly.toml app configuration file generated for agebot-lrkt on 2025-07-29T21:25:36+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'agebot-lrkt'
primary_region = 'waw'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[processes]
app = "python main.py"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
